name: deploy-test

on:
  push:
    branches: 
      - "main"
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: mkdir # 设置 id_rsa
      run: mkdir test

